---
name: 🐛 Bug Report
about: Create a report to help us improve the VSCode extension
title: ''
labels: bug
assignees: ''

---

## Description

Please describe the issue you are experiencing with the VSCode extension.

---

## Environment

- **Operating System:** <!-- e.g., Windows 11, macOS 13, Ubuntu 22.04 -->
- **Shell:** <!-- e.g., bash, zsh, PowerShell, cmd -->
- **Project Structure:** <!-- MonoRepo / Single Project -->
- **VSCode Version:** <!-- e.g., 1.90.0 -->

---

## Steps to Reproduce

1. 
2. 
3. 

---

## Expected Behavior

Describe what you expected to happen.

---

## Actual Behavior

Describe what actually happened.

---

## Test Command Output

If applicable, please provide the full output of the test command you ran.

