module.exports = {
    collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}'],
    coverageDirectory: './coverage',
    coverageReporters: ['json-summary', 'text'],
    displayName: 'yara-eu-plus',
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
    moduleNameMapper: {
        '\\.(css|less)$': 'identity-obj-proxy',
        '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|avif)$':
            '<rootDir>/src/testing/fileMock.cjs',
        '@/src/(.*)': '<rootDir>/src/$1',
        '^virtual:__federation__$': '<rootDir>/__mocks__/virtual-federation.ts',
    },
    passWithNoTests: true,
    resetMocks: true,
    restoreMocks: true,
    //setupFiles: ['<rootDir>/src/testing/setupTestEnv.ts', 'whatwg-fetch'], // required for testing with react-router data API
    //setupFilesAfterEnv: ['<rootDir>/src/testing/setupTests.ts'],
    testEnvironment: 'jsdom',
    testRegex: 'src/.*\\.spec\\.[tj]sx?',
    transformIgnorePatterns: [
        `/node_modules/(?!(${[
            '.*-separated-tokens',
            '@faker-js',
            '@mapbox',
            '@yaradigitallabs',
            'bail',
            'd3-.*',
            'decode-named-character-reference',
            'devlop',
            'hast-util-to-jsx-runtime',
            'hast-util-whitespace',
            'html-url-attributes',
            'internmap',
            'is-plain-obj',
            'mdast-.*',
            'micromark.*',
            'nanoid',
            'property-information',
            'react-error-boundary',
            'react-hotkeys-hook',
            'react-markdown',
            'remark-.*',
            'robust-predicates',
            'trim-lines',
            'trough',
            'unified',
            'unist-.*',
            'vfile',
            'vfile-message',
        ].join('|')})/)`,
    ],
    // watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
    rootDir: '.',
};
